# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/casse/Enseignement/eclipse-workspace/PhySim

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/casse/Enseignement/eclipse-workspace/PhySim

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/casse/Enseignement/eclipse-workspace/PhySim/CMakeFiles /home/casse/Enseignement/eclipse-workspace/PhySim/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/casse/Enseignement/eclipse-workspace/PhySim/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sat

# Build rule for target.
sat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sat
.PHONY : sat

# fast build rule for target.
sat/fast:
	$(MAKE) -f CMakeFiles/sat.dir/build.make CMakeFiles/sat.dir/build
.PHONY : sat/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/sat.dir/build.make CMakeFiles/sat.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/sat.dir/build.make CMakeFiles/sat.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/sat.dir/build.make CMakeFiles/sat.dir/main.cpp.s
.PHONY : main.cpp.s

src/Model.o: src/Model.cpp.o

.PHONY : src/Model.o

# target to build an object file
src/Model.cpp.o:
	$(MAKE) -f CMakeFiles/sat.dir/build.make CMakeFiles/sat.dir/src/Model.cpp.o
.PHONY : src/Model.cpp.o

src/Model.i: src/Model.cpp.i

.PHONY : src/Model.i

# target to preprocess a source file
src/Model.cpp.i:
	$(MAKE) -f CMakeFiles/sat.dir/build.make CMakeFiles/sat.dir/src/Model.cpp.i
.PHONY : src/Model.cpp.i

src/Model.s: src/Model.cpp.s

.PHONY : src/Model.s

# target to generate assembly for a file
src/Model.cpp.s:
	$(MAKE) -f CMakeFiles/sat.dir/build.make CMakeFiles/sat.dir/src/Model.cpp.s
.PHONY : src/Model.cpp.s

src/Monitor.o: src/Monitor.cpp.o

.PHONY : src/Monitor.o

# target to build an object file
src/Monitor.cpp.o:
	$(MAKE) -f CMakeFiles/sat.dir/build.make CMakeFiles/sat.dir/src/Monitor.cpp.o
.PHONY : src/Monitor.cpp.o

src/Monitor.i: src/Monitor.cpp.i

.PHONY : src/Monitor.i

# target to preprocess a source file
src/Monitor.cpp.i:
	$(MAKE) -f CMakeFiles/sat.dir/build.make CMakeFiles/sat.dir/src/Monitor.cpp.i
.PHONY : src/Monitor.cpp.i

src/Monitor.s: src/Monitor.cpp.s

.PHONY : src/Monitor.s

# target to generate assembly for a file
src/Monitor.cpp.s:
	$(MAKE) -f CMakeFiles/sat.dir/build.make CMakeFiles/sat.dir/src/Monitor.cpp.s
.PHONY : src/Monitor.cpp.s

src/Port.o: src/Port.cpp.o

.PHONY : src/Port.o

# target to build an object file
src/Port.cpp.o:
	$(MAKE) -f CMakeFiles/sat.dir/build.make CMakeFiles/sat.dir/src/Port.cpp.o
.PHONY : src/Port.cpp.o

src/Port.i: src/Port.cpp.i

.PHONY : src/Port.i

# target to preprocess a source file
src/Port.cpp.i:
	$(MAKE) -f CMakeFiles/sat.dir/build.make CMakeFiles/sat.dir/src/Port.cpp.i
.PHONY : src/Port.cpp.i

src/Port.s: src/Port.cpp.s

.PHONY : src/Port.s

# target to generate assembly for a file
src/Port.cpp.s:
	$(MAKE) -f CMakeFiles/sat.dir/build.make CMakeFiles/sat.dir/src/Port.cpp.s
.PHONY : src/Port.cpp.s

src/Simulation.o: src/Simulation.cpp.o

.PHONY : src/Simulation.o

# target to build an object file
src/Simulation.cpp.o:
	$(MAKE) -f CMakeFiles/sat.dir/build.make CMakeFiles/sat.dir/src/Simulation.cpp.o
.PHONY : src/Simulation.cpp.o

src/Simulation.i: src/Simulation.cpp.i

.PHONY : src/Simulation.i

# target to preprocess a source file
src/Simulation.cpp.i:
	$(MAKE) -f CMakeFiles/sat.dir/build.make CMakeFiles/sat.dir/src/Simulation.cpp.i
.PHONY : src/Simulation.cpp.i

src/Simulation.s: src/Simulation.cpp.s

.PHONY : src/Simulation.s

# target to generate assembly for a file
src/Simulation.cpp.s:
	$(MAKE) -f CMakeFiles/sat.dir/build.make CMakeFiles/sat.dir/src/Simulation.cpp.s
.PHONY : src/Simulation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... sat"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/Model.o"
	@echo "... src/Model.i"
	@echo "... src/Model.s"
	@echo "... src/Monitor.o"
	@echo "... src/Monitor.i"
	@echo "... src/Monitor.s"
	@echo "... src/Port.o"
	@echo "... src/Port.i"
	@echo "... src/Port.s"
	@echo "... src/Simulation.o"
	@echo "... src/Simulation.i"
	@echo "... src/Simulation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

